import { Images } from './../theme/images';

export const welcomedata = [
  {
    id: 0,
    title: 'Politics',
    src: Images.welcomepolitics,
    is_selected: false,
    subpart: 'MH',
  },
  {
    id: 1,
    title: 'Histroy',
    src: Images.welcomehistroy,
    is_selected: false,
    subpart: 'MH',
  },
  {
    id: 2,
    title: 'Science',
    src: Images.welcomescience,
    is_selected: false,
    subpart: 'MH',
  },
  {
    id: 3,
    title: 'Law',
    src: Images.welcomelaw,
    is_selected: false,
    subpart: 'MH',
  },
  {
    id: 4,
    title: 'Food',
    src: Images.welcomefood,
    is_selected: false,
    subpart: 'MH',
  },
  {
    id: 5,
    title: 'Medical',
    src: Images.welcomemedical,
    is_selected: false,
    subpart: 'MH',
  },
  {
    id: 6,
    title: 'Design',
    src: Images.welcomedesign,
    is_selected: false,
    subpart: 'MH',
  },
  {
    id: 7,
    title: 'Culture',
    src: Images.welcomeculture,
    is_selected: false,
    subpart: 'MH',
  },
  {
    id: 8,
    title: 'Sport',
    src: Images.welcomesport,
    is_selected: false,
    subpart: 'MH',
  },
  {
    id: 9,
    title: 'Politics',
    src: Images.welcomepolitics,
    is_selected: false,
    category: 'Travel',
    subpart: 'MH',
  },
  {
    id: 10,
    title: 'Histroy',
    src: Images.welcomehistroy,
    is_selected: false,
    subpart: 'MH',
  },
  {
    id: 11,
    title: 'Science',
    src: Images.welcomescience,
    is_selected: false,
    category: 'Travel',
    subpart: 'MH',
  },
  {
    id: 12,
    title: 'Law',
    src: Images.welcomelaw,
    is_selected: false,
    subpart: 'MH',
  },
  {
    id: 13,
    title: 'Politics',
    src: Images.welcomepolitics,
    is_selected: false,
    subpart: 'MH',
  },
  {
    id: 14,
    title: 'Histroy',
    src: Images.welcomehistroy,
    is_selected: false,
    subpart: 'GJ',
  },
  {
    id: 15,
    title: 'Science',
    src: Images.welcomescience,
    is_selected: false,
    subpart: 'GJ',
  },
  {
    id: 16,
    title: 'Law',
    src: Images.welcomelaw,
    is_selected: false,
    subpart: 'GJ',
  },
  {
    id: 17,
    title: 'Food',
    src: Images.welcomefood,
    is_selected: false,
    subpart: 'GJ',
  },
  {
    id: 18,
    title: 'Medical',
    src: Images.welcomemedical,
    is_selected: false,
    subpart: 'GJ',
  },
  {
    id: 19,
    title: 'Design',
    src: Images.welcomedesign,
    is_selected: false,
    subpart: 'GJ',
  },
  {
    id: 20,
    title: 'Culture',
    src: Images.welcomeculture,
    is_selected: false,
    subpart: 'GJ',
  },
  {
    id: 21,
    title: 'Sport',
    src: Images.welcomesport,
    is_selected: false,
    subpart: 'GJ',
  },
  {
    id: 22,
    title: 'Politics',
    src: Images.welcomepolitics,
    is_selected: false,
    subpart: 'GJ',
  },
  {
    id: 23,
    title: 'Histroy',
    src: Images.welcomehistroy,
    is_selected: false,
    subpart: 'GJ',
  },
  {
    id: 24,
    title: 'Science',
    src: Images.welcomescience,
    is_selected: false,
    subpart: 'GJ',
  },
  {
    id: 25,
    title: 'Law',
    src: Images.welcomelaw,
    is_selected: false,
    subpart: 'GJ',
  },
  {
    id: 26,
    title: 'Law',
    src: Images.welcomelaw,
    is_selected: false,
    subpart: 'GJ',
  },
];
